  
owner: ivao-portugal
repo: status-page

# Monitored sites
sites:
  - name: Website
    url: https://pt.ivao.aero/portal
  - name: Events
    url: https://events.pt.ivao.aero
  - name: API
    url: $API_ENDPOINT

status-website:
  cname: status.pt.ivao.aero # Custom CNAME
  logoUrl: https://pt.ivao.aero/assets/symbol_no_margin_white.png
  favicon: https://pt.ivao.aero/assets/symbol_no_margin.png
  name: IVAO PT Systems Status
  introTitle: "This is an overview of our Systems."
  introMessage: On this page you can check each one of our services status and also see planned maintenances.
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://pt.ivao.aero/portal
  links:
    - rel: stylesheet
      href: https://status.pt.ivao.aero/custom.css
