  
owner: ivao-portugal
repo: status-page

# Monitored sites
sites:
  - name: Website
    url: https://pt.ivao.aero/portal
  - name: Events
    url: https://events.pt.ivao.aero
  - name: Discord Bot (Weather)
    method: GET
    url: $HK_ENDPOINT
    icon: https://discord.com/assets/41484d92c876f76b20c7f746221e8151.svg
    headers:
      - "Accept: application/vnd.heroku+json; version=3"
      - "Authorization: Bearer $HK_TOKEN"

status-website:
  cname: status.pt.ivao.aero # Custom CNAME
  logoUrl: https://pt.ivao.aero/portal/wp-content/uploads/2021/05/IG-PROFILE-PICTURE.png
  name: IVAO PT Systems Status
  introTitle: "This is an overview of our Systems."
  introMessage: On this page you can check each one of our services status and also see planned maintenances.
  navbar:
    - title: Status
      href: /status-page
    - title: Website
      href: https://pt.ivao.aero/portal
